language: node_js

node_js:
  - "stable"

cache:
  directories:
  - node_modules

script:
  - npm run lint:js
  - npm test
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: dist
  verbose: true