language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm install
  - npm run build
  - npm run github-pages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  on:
    branch: master